[tool.poetry]
name = "data-fraude"
version = "0.1.0"
description = ""
authors = ["Andreza <dedezasilva@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
